#!/usr/bin/env bash

export MEETUP_API_KEY="{MEETUPAPIKEY}" 
export MEETUP_GROUP_NAME="{MEETUPGROUPNAME}" 
export TWITTER_CONSUMER_KEY="{TWITTERCONSUMERKEY}" 
export TWITTER_CONSUMER_SECRET="{TWITTERCONSUMERSECRET}" 
export TWITTER_ACCESS_TOKEN="{TWITTERACCESSTOKEN}" 
export TWITTER_ACCESS_TOKEN_SECRET="{TWITTERACCESSTOKENSECRET}"